### PR TITLE
Fix crash when functions sorts empty stream

### LINKED ISSUE #7573: Assertion error in sorting
## Description

Assertion error causes crash in sorting.

## Environment

TypeDB CE 3.5.0

## Reproducible Steps

1. Set up

Boot TypeDB 3.5.0, and load the bookstore example:

2. Execute
```
with fun first_contributor($book: book) -> { contributor }:
  match
  $contributor isa contributor, has name $name;
  authoring ($contributor, $book);
  sort $name;
  limit 1;
  return { $contributor };
match
$book isa book, has title $title;
let $first-contributor = first_contributor($book);
$first-contributor has name $name;
sort $title, $name;
fetch {
  "title": $title,
  "contributor": $name,
};
```

3. Unexpected result
```

Ready!
thread 'tokio-runtime-worker' panicked at executor/read/collecting_stage_executor.rs:217:34:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

### PR DESCRIPTION
**Pull request by krishnangovindraj**
## Product change and motivation
Fixes a crash when a functions tried to sort an empty stream.

## Implementation
Does some refactoring so the `output_width` is known when the collector is created, rather than having to wait for the first row (which may not come, and caused the collecting batch to be uninitialised).

- Fixes #7573

### CODE REVIEW

File: compiler/executable/pipeline.rs [hunk 1]
```diff
@@ -397,14 +397,6 @@ fn compile_stage(
             ExecutableStage::Offset(Arc::new(OffsetExecutable::new(offset.offset(), stage_input_positions.clone()))),
             BTreeSet::new(),
         )),
-        AnnotatedStage::Sort(sort) => Ok((
```
Comment (krishnangovindraj) [inline compiler/executable/pipeline.rs:400]: Strangely duplicated.

File: executor/batch.rs [hunk 2]
```diff
@@ -120,6 +120,8 @@ impl<'a> From<MaybeOwnedRow<'a>> for FixedBatch {
 }
 
 impl IntoIterator for FixedBatch {
+    type Item = MaybeOwnedRow<'static>;
+
```
Comment (krishnangovindraj) [inline executor/batch.rs:124]: linter wanted to reorder.

File: executor/read/collecting_stage_executor.rs [hunk 3]
```diff
@@ -126,7 +137,6 @@ pub(super) trait CollectedStageIteratorTrait {
 // Reduce
 pub(super) struct ReduceCollector {
     active_reducer: GroupedReducer,
-    output: Option<BatchRowIterator>,
```
Comment (krishnangovindraj) [inline executor/read/collecting_stage_executor.rs:129]: Unused, and probably forgotten after a previous refactor

File: executor/read/stream_modifier.rs [hunk 4]
```diff
@@ -22,7 +22,7 @@ pub(crate) enum StreamModifierExecutor {
     Select { inner: PatternExecutor, removed_positions: Vec<VariablePosition> },
     Offset { inner: PatternExecutor, offset: u64 },
     Limit { inner: PatternExecutor, limit: u64 },
-    Distinct { inner: PatternExecutor, output_width: u32 },
```
Comment (krishnangovindraj) [inline executor/read/stream_modifier.rs:25]: Current implementation doesn't need to know.

File: executor/read/stream_modifier.rs [hunk 5]
```diff
@@ -266,7 +274,9 @@ impl LastMapper {
 impl StreamModifierResultMapperTrait for LastMapper {
     fn map_output(&mut self, subquery_result: Option<FixedBatch>) -> Option<FixedBatch> {
         if let Some(input_batch) = subquery_result {
-            self.last_row = Some(input_batch.get_row(input_batch.len() - 1).into_owned());
+            self.last_row = (!input_batch.is_empty()).then(|| {
+                input_batch.get_row(input_batch.len() - 1).into_owned()
+            });
```
Comment (krishnangovindraj) [inline executor/read/stream_modifier.rs:279]: Possible edge case in the case of an empty batch

File: compiler/executable/pipeline.rs (hunk 1 above)
Comment (flyingsilverfin) [reply compiler/executable/pipeline.rs:400]: How is that possible when it i was a `match` clause??

Comment (krishnangovindraj) [reply compiler/executable/pipeline.rs:400]: Turned yellow as "unreachable" but didn't break.
