### PR TITLE
Fix rule satisfiability validation

### LINKED ISSUE #6227: Rule validation doesn't catch != between non-attributes
## Description

Rule validation fails to catch invalid rules where `!=` is used between entities.

## Environment

1. OS (where Grakn server runs): Mac OS 10
2. Grakn version (and platform): 2.0 alpha 8
3. Grakn client: console

## Reproducible Steps

Steps to create the smallest reproducible scenario:

Loading the [docs schema](https://github.com/graknlabs/docs/blob/development/files/social-network/schema.gql) completes successfully, despite the fact that this rule is present:
```
rule friends-excluded-permission:
		when {
			(content: $sc, by: $sb, hidden-from: $hf) isa friends-with-exclusion-sharing;
			(friend: $sb, $f) isa friendship;
			$f != $hf;
		} then {
			(content: $sc, grantee: $f) isa content-permission;
		};
```
This lead to the fact that nothing is inferred when querying `match (content: $sc, grantee: $f) isa content-permission;`. No error is thrown in the server logs.

## Expected Output

TypeResolver should have thrown an error when trying to load the schema.

### PR DESCRIPTION
**Pull request by flyingsilverfin**
## What is the goal of this PR?
We previously checked that a rule is coherent/satisfiability by checking each variable in the `when` and the `then`. However, we no longer set the satisfiability of a variable at all, instead setting only `isCoherent` at the conjunction. This PR updates Rule validation to reflect this change and removes `isSatisfiable` from `Variable`

Fixes #6227 

## What are the changes implemented in this PR?
* Fix rule validation
* Add a new test case to test `when` validation, extending the current `then` validation
* Remove `isSatisfiable` getters and setters from `Variable`

### CODE REVIEW

File: logic/Rule.java [hunk 1]
```diff
@@ -198,19 +196,12 @@ void validateCycles() {
...
-                                         .findFirst().ifPresent(whenVar -> {
-                                     if (thenVar.resolvedTypes().isEmpty() && thenVar.isSatisfiable()) {
-                                         thenVar.addResolvedTypes(whenVar.resolvedTypes());
-                                     } else thenVar.retainResolvedTypes(whenVar.resolvedTypes());
-                                     if (thenVar.resolvedTypes().isEmpty()) thenVar.setSatisfiable(false);
-                                 })
-                );
+                .forEach(thenVar -> {
+                    Variable whenVar = when.variable(thenVar.id());
+                    thenVar.retainResolvedTypes(whenVar.resolvedTypes());
```
Comment (jmsfltchr) [inline logic/Rule.java:202]: What happens if the when variable's resolvedTypes is empty? (In the case it could be any Thing)

**Review by jmsfltchr — APPROVED** [review]

File: logic/Rule.java (hunk 1 above)
Comment (jmsfltchr) [reply logic/Rule.java:202]: This is now impossible as an empty set of types indicates failure, and need indicates "all types".
