### PR TITLE
Only seek iterators in k-way merge when behind

### LINKED ISSUE #7446: Unreachable code on iterator seek
## Description
```
thread 'tokio-runtime-worker' panicked at executor/instruction/iterator.rs:106:21:
internal error: entered unreachable code: Key behind the stored item in a Peekable iterator
```

## Environment

1. TypeDB distribution: Core
2. TypeDB version: 3.2.0-rc2
3. Environment: Mac
4. Client and version: studio, but unlikely to matter
5. Other details:

## Reproducible Steps

1. Set up
Run `load.py` from the [this .zip](https://github.com/user-attachments/files/19971656/seek-bug-social-network.zip)

3. Test/Query
```
match
  $me isa person, has name $name; $name == "Anna Thomas";
  $post isa post; $posting isa posting, links (author: $me, post: $post);
  $engagement isa content-engagement; not { $engagement isa! posting; };
  $engagement links (author: $other-person, $engagement-role: $post);
  $organisation isa organisation; 
  { $rel isa employment, links (employer: $organisation, employee: $other-person); } or 
  { $rel isa education, links (institute:$organisation, attendee: $other-person); };
  $other-person has name $other-name;
  $organisation has name $org-name;
```
Or minimally:
```
match
  $me isa person, has name $name; 
  $post isa post; $posting isa posting, links (author: $me, post: $post);
  $engagement links (author: $other-person, $engagement-role: $post);
#$name == "Anna Thomas"; # For less results
  ```

4. Unexpected result
Server crash:
```
thread 'tokio-runtime-worker' panicked at executor/instruction/iterator.rs:106:21:
internal error: entered unreachable code: Key behind the stored item in a Peekable iterator
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Expected result
A handful of results.

# Additional Information
Relevant stack trace:

```
10:        0x103f964ec - core::panicking::panic_fmt::ha4b80a05b9fff47a
  11:        0x103227cbc - <lending_iterator::Peekable<I> as executor::instruction::iterator::TupleSeekable>::seek::ha1a393e5671f240b
  12:        0x1032314b4 - <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next::h37ed29a812abc86f
  13:        0x1032192cc - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::hdf5af700b913c3ce
  14:        0x10322b17c - <alloc::collections::binary_heap::BinaryHeap<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::h12f3bd1d3753e20a
  15:        0x103234ab0 - core::iter::adapters::try_process::hb0db90d7f786ce5c
  16:        0x103247e68 - <lending_iterator::kmerge::KMergeBy<I,fn((&core::result::Result<executor::instruction::tuple::Tuple,alloc::boxed::Box<concept::error::ConceptReadError>>,&core::result::Result<executor::instruction::tuple::Tuple,alloc::boxed::Box<concept::error::ConceptReadError>>)) .> core::cmp::Ordering> as executor::instruction::iterator::TupleSeekable>::seek::h175f9f222c6df6a8
  17:        0x103209a50 - executor::instruction::iterator::TupleIterator::skip_until_first_unbound_value::h2da31824f0cbe6ab
  18:        0x10325d760 - executor::read::immediate_executor::IntersectionExecutor::find_intersection::h28fa9d1b0ba0e245
  19:        0x1027b861c - executor::read::immediate_executor::IntersectionExecutor::compute_next_row::hce04c960c5b28286
  20:        0x1027b2f08 - executor::read::immediate_executor::ImmediateExecutor::batch_continue::h68c582d2bf6d1f74
  21:        0x10290fc38 - executor::read::pattern_executor::PatternExecutor::batch_continue::hc7197a9ceea76fc4
```

### LINKED ISSUE #7577: Index edge assertion failure on delete
## Description

When deleting a relation, we get an assertion error in the indexed shortcut edges.

## Environment

TypeDB CE 3.5.0-rc0

**Run in debug, not release mode to keep assertions**

## Reproducible Steps

1. Set up
Load bookstore example:

```
typedb console '--username=admin' '--address=localhost:1729' --tls-disabled --password='password' --command="database delete bookstore" --command="database create-init bookstore https://github.com/typedb/typedb-examples/releases/download/3.5.2/bookstore-schema.tql https://github.com/typedb/typedb-examples/releases/download/3.5.2/bookstore-data.tql"
```

2. Execute

```
match $retracted_review isa review, has id "r0001"; $rel links ($retracted_review); delete $rel;
```

3. Error: 

```

thread 'tokio-runtime-worker' panicked at concept/thing/relation.rs:444:13:
assertion failed: !player.get_indexed_relations(snapshot, thing_manager, self.type_(),
            storage_counters.clone()).is_ok_and(|mut iterator|
            iterator.any(|result|
                    {
                        match result {
                            Ok(((start, _, _, _, start_role, _), _)) =>
                                start == player && start_role == role,
                            Err(_) => false,
                        }
                    }))

```

## Additional information

Relevant logs from TypeDB or Driver:

### PR DESCRIPTION
**Pull request by dmitrii-ubskii**
## Product change and motivation

Fix intermittent crashes with `Key behind the stored item in a Peekable iterator` when a roleplayer index constraint is part of a join.

## Implementation

In general, it is considered an error to seek an iterator that is already ahead of the seek target. We cannot seek backwards, and we cannot guarantee that the iterator is pointing at the element one after the target, which is what the caller code expects.

In a `Peekable<I>`, if the peeked item is behind the target, but the tip of the iterator `I` is ahead _and_ the `I` can detect that (being another `Peekable` at some level), we run into an issue where this condition is checked multiple times, causing a crash.

We relax this constraint to only apply to `Peekable`. When `seek` is called, it peeks the current item in the iterator (panicking if `seek` was used incorrectly to avoid illegal state), then, if needed, calls `seek` on the inner iterator which advances unconditionally.

Closes #7577, closes #7446.

### CODE REVIEW

File: common/lending_iterator/kmerge.rs [hunk 1]
```diff
@@ -99,7 +99,12 @@ where
             self.find_next_state();
         }
         if let Some(next_iterator) = &mut self.next_iterator {
-            next_iterator.iter.seek(key);
+            next_iterator.iter.peek();
+            if let Some(item) = next_iterator.iter.get_peeked() {
```
Comment (flyingsilverfin) [inline common/lending_iterator/kmerge.rs:103]: why not use the same `next_iterator.iter.peek()` the same way we have it below?

Comment (dmitrii-ubskii) [reply common/lending_iterator/kmerge.rs:103]: Lifetime issues. `peek` borrows `iter` mutably, so we can't also call `compare_key` on it while `item` is alive. `get_peeked` borrows it immutably though, so that's fine.
We're using the same `peek(); if let ... = get_peeked()` below too.

**Review by flyingsilverfin — APPROVED** [review]
